paths:
  /api/products:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        "200":
          description: All products
        "500":
          description: Server error

  /api/products/{id}:
    get:
      summary: Get product by id
      tags:
        - Products
      parameters:
        - name: id
          in: path
          description: Product identifier
      responses:
        "200":
          description: One product found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
              example:
                id: fjktjkfdjlkgtjklfjlkg
                title: El rey leon
                description: Pelicula animada 
                price: 4500
                stock: 20
                code: 1234
                category: Infantiles
                thumbnail: www.linkdelaimagen.com.ar
                status: true
                owner: admin
        "500":
          description: Server error

    put:
      summary: Update product by id
      tags:
        - Products
      parameters:
        - name: id
          in: path
          description: Product identifier
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
            example:
              title: El rey leon
              description: Pelicula animada 
              price: 4500
              stock: 30
              code: 1234
              category: Infantiles
              thumbnail: www.linkdelaimagen.com.ar
              status: true
              owner: admin
      responses:
        "200":
          description: Product updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
              example:
                id: fjktjkfdjlkgtjklfjlkg
                title: El rey leon
                description: Pelicula animada 
                price: 4500
                stock: 30
                code: 1234
                category: Infantiles
                thumbnail: www.linkdelaimagen.com.ar
                status: true
                owner: admin
        "500":
          description: Server error

    post:
      summary: Created a new product
      tags:
        - Products
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
            example:
              title: El rey leon
              description: Pelicula animada 
              price: 4500
              stock: 30
              code: 1234
              category: Infantiles
              thumbnail: www.linkdelaimagen.com.ar
              status: true
              owner: admin
      responses:
        "200":
          description: Product created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
              example:
                id: fjktjkfdjlkgtjklfjlkg
                title: El rey leon
                description: Pelicula animada 
                price: 4500
                stock: 30
                code: 1234
                category: Infantiles
                thumbnail: www.linkdelaimagen.com.ar
                status: true
                owner: admin
        "400":
          description: All fields required
        "500":
          description: Server error

    delete:
      summary: Delete product by id
      tags:
        - Products
      parameters:
        - name: id
          in: path
          description: Product identifier
      # requestBody:
      #   content:
      #     application/json:
      #       schema:
      #         $ref: "#/components/requestBodies/deletedProduct"
      responses:
        "200":
          description: Product deleted
        "400":  
          description: Product not found
        "500":
          description: Server error or This product was not created by you

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: number
        code:
          type: number
        category:
          type: string
        thumbnail:
          type: string
        status:
          type: boolean
        owner:
          type: string
      example:
        id: fjktjkfdjlkgtjklfjlkg
        title: El rey leon
        description: Pelicula animada 
        price: 4500
        stock: 20
        code: 1234
        category: Infantiles
        thumbnail: www.linkdelaimagen.com.ar
        status: true
  requestBodies:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: number
        code:
          type: number
        category:
          type: string
        thumbnail:
          type: string
        status:
          type: boolean
        owner:
          type: string